# Generated by Django 3.0.6 on 2020-05-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='change_dir',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('src_dir', models.CharField(max_length=255)),
                ('ipaddr', models.CharField(max_length=15)),
                ('change_time', models.CharField(max_length=30)),
                ('add_time', models.CharField(max_length=30)),
                ('event_type', models.CharField(max_length=10)),
            ],
        ),
    ]
